name: background_task_example
description: "Demonstrates how to use the background_task plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  background_task:
    path: ../

  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  pedantic_mono:

flutter:
  uses-material-design: true
